name: Deploy phase-service to QA

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: qa

    env:
      HOST: ${{ secrets.EC2_PHASE_QA_IP }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PHASE_QA_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Deploy to EC2 QA
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@$HOST << 'EOF'
            sudo dnf update -y
            sudo dnf install -y git docker tar gzip curl iptables
            sudo systemctl enable --now docker
            sudo usermod -aG docker ec2-user

            # Docker Compose v2
            sudo mkdir -p /usr/local/lib/docker/cli-plugins
            sudo curl -SL https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-linux-x86_64 \
              -o /usr/local/lib/docker/cli-plugins/docker-compose
            sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose

            # .NET SDK 7.0 (manual installation)
            curl -O https://download.visualstudio.microsoft.com/download/pr/4f8c1232-01b3-4fc2-88d2-d86ae1b308a2/dcbe5f61fbc3a12f5d1d76c3503fa587/dotnet-sdk-7.0.400-linux-x64.tar.gz
            sudo mkdir -p /opt/dotnet
            sudo tar zxf dotnet-sdk-7.0.400-linux-x64.tar.gz -C /opt/dotnet
            sudo ln -sf /opt/dotnet/dotnet /usr/local/bin/dotnet

            cd /home/ec2-user
            if [ ! -d phase-service ]; then
              git clone --branch qa https://github.com/league-platform/phase-service.git
            fi

            cd phase-service
            sudo chown -R ec2-user:ec2-user .
            git config --global --add safe.directory /home/ec2-user/phase-service
            git reset --hard
            git pull origin qa

            sudo docker compose down || true
            sudo docker compose up -d --build
          EOF




